Support for Bio Multi-protocol keys
Yubico/yubikit-ios pull request #157
Opened 2024-06-19 09:16 UTC by jensutbult

2024-06-24 12:32 UTC, AdamVe requested changes
I found some code snippets to review. 🕵🏻‍♂️

2024-06-24 12:32 UTC, AdamVe commented on YubiKit/YubiKit/Connections/Shared/Sessions/MGMT/YKFManagementSession.h
> +///    Response block for [deviceReset:completion:] which will do a device reset on a YubiKey Biuo
Biuo -> Bio

2024-06-24 12:32 UTC, AdamVe commented on YubiKit/YubiKit/Connections/Shared/Errors/YKFInvalidPinError.h
> +//
I saw in other files you update this to a different header, maybe you forgot here?

2024-06-24 12:32 UTC, AdamVe commented on YubiKit/YubiKit/Connections/Shared/Errors/YKFInvalidPinError.m
> +//
This header is different than in other files.

2024-06-24 12:32 UTC, AdamVe commented on YubiKit/YubiKit/Connections/Shared/Sessions/PIV/YKFPIVSession.m
> +            }
Review this part - if verification of the temporary PIN fails, the error.code will be 0x63C0, so there is no need to get the retries.

2024-06-25 08:05 UTC, AdamVe approved these changes
LGTM

2024-06-25 08:09 UTC, dainnilsson approved these changes

2024-06-25 08:29 UTC, merged